### ISSUE TITLE
Confusing parts of the license text (suggestions from a non-lawyer)

### ISSUE THREAD

**Issue by roryokane** [keygen-sh/fcl.dev#1]
I am not a lawyer, but I think the [license text](https://github.com/keygen-sh/fcl.dev/blob/master/FCL-1.0-MIT.md) could be improved. Some parts seem needlessly confusing.

> ### Licensor ("We")
>
> The party offering the Software under these Terms and Conditions.

In combination with the definition of Competing Use as a substitute for a “product or service we offer using the Software”, and the Redistribution section requiring this license to propagate, this definition seems to have the effect of making the definition of Competing Uses strangely flexible.

Say the Software in this context is an in-memory database. The original authors, Company A, use it in their web app for filing insurance claims. They publish the software under this license. Writing an app for filing insurance claims would be a Competing Use – fine.

Company B gets this source code, modifies it, uses it to write a web app for tracking package delivery, and redistributes that source code. For this modified version, isn’t Company B the Licensor (“We”)? That would mean that if Company C wants to use that software to write a app for filing insurance claims, it wouldn’t be a Competing Use, even though they’re competing with Company A.

Ah, now I see the “licensor name” variable in the Notice section. But when the license is filled out, the Notice section of the license will just say “Copyright 2024 Company A”. It’s not clear that “the party offering the Software under these Terms and Conditions” is supposed to refer to that same company, no matter who forks the software. Why not write “the company whose name is in the Notice section” instead? (I’m assuming that those who fork the software are not allowed to remove Company A from the Notice section because Company A retains copyright in the software.)

> ### Disclaimer
>
> THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES …

The disclaimer is [needlessly](https://web.archive.org/web/20190330115632/https://lemminglaw.com/#conspicuous-does-not-mean-all-caps) hard to read by being in all caps. (The MIT License has the same problem, but writers of new licenses don’t have to make the same mistakes.) One way to improve readability would be to write in sentence case and format the paragraph in bold and italics, as the [Blue Oak Model License 1.0.0](https://blueoakcouncil.org/license/1.0.0#html) does.

> In the event the provision of this Disclaimer section are enforceable under applicable law, the license herein is void.

“The provision … are” is ungrammatical. I see conflicting definitions of “provision” when I look online, but it seems likely that, if either of the previous paragraphs counts as a provision, then each would count as separate provisions. So it should be “the provisions … are”.

Doesn’t this sentence then mean that if the previous two paragraphs are legal to enforce, then the whole license is void? I presume you intended the previous two paragraphs to be enforceable, but that would mean the whole license is meaningless. Did you mean to write “unenforceable” instead of “enforceable”? Or did you mean “If you try to hold us liable (by suing us) despite this disclaimer, the license is void”? If the latter, there must be a clearer way to write that.

It’s also confusing that you refer to “the license herein”. The heading of the whole file calls it a “License”, but most other clauses refer to just the Terms and Conditions subsection of it. There is also Future License below this. Which is intended to become void? (The file also mentions “license key functionality in the Software”, but that would not be “herein”, so it’s probably not that.)

**Comment by ezekg** [comment]
Thanks for the feedback. The FCL's license text is largely taken from the Functional Source License, and feedback can be submitted at https://github.com/getsentry/fsl.software if needed. It's my goal with the FCL to stay as close as possible to the original FSL, so any major changes would preferably be made upstream.

But I do want to speak to your initial comment on competing use. If company B were to create a derivative work of company A's software which is licensed under the FCL, company A is still the licensor of their code — you cannot retroactively claim copyright of an existing work. Any modifications company B makes to the software are theirs, but all other code still belongs to company A and is licensed by company A to company B and anybody else using it under the FCL. So all code that is licensed by company A still has their non-compete, and code written by company B has their non-compete.

This is how other software licenses work too, and the FCL specifically covers this under [Redistribution](https://github.com/keygen-sh/fcl.dev/blob/master/FCL-1.0-MIT.md#redistribution) saying that you cannot remove copyright notices. Recent examples of this happening in the real-world while retaining existing copyright notices include OpenTofu and Valkey, which are forks of Terraform and Redis, respectively:

- https://github.com/opentofu/opentofu/blob/main/LICENSE
- https://github.com/valkey-io/valkey/blob/unstable/COPYING

You do mention some FCL-specific notes though, like the "enforceable" vs "unenforceable" question, so I'm going to cc @hmeeker. Re: all-caps formatting — the license is written in plain text and may be embedded in source code via a comment, so we can't use italics or bold text for emphasis, so all caps seems like a good well-used alternative.

**Comment by ezekg** [comment]
@roryokane I've removed the confusing verbiage in the Disclaimer to bring the FCL back in line with the FSL.

Thanks for the early feedback. I really do appreciate it.

**Comment by ezekg** [comment]
Going to close this since the actionable item has been fixed in https://github.com/keygen-sh/fcl.dev/commit/78faf73bdec18f3318be21b2a6682b3bf9a6ab64.
