### ISSUE TITLE
"direct competition"

### ISSUE THREAD

**Issue by Dieterbe** [keygen-sh/fcl.dev#2]
Hello!

I see on fcl.dev that you introduce the term "direct" competition

> What is a competing use under the FCL?  Under the FCL, a competing use is any use case that competes with the business interests of the author. For most projects licensed under the FCL, this will mean direct SaaS competition, (...)
> (...) But since the FCL transitions to Open Source after 2 years, any user is free to use an Open Source version of the project for direct competition.

and on X, it seems you separate competition from "direct" competition
(https://x.com/keygen_sh/status/1820883043386847268)

It seems to me, introducing the word "direct" does harm than good. legally, it means nothing (AFAIK), and colloquially it means something different.

Colloqually, i believe indirect competition is like netflix vs blockbuster (both delivering entertainment, but via very different services/products) and direct competition is like netflix vs disney streaming (both streaming content).  note that netflix and disney may use very different software stacks to achieve this). The competition which FSL and FCL forbid is when delivering the same (or similar) service, using the same fair source software.

I don't see the usage of the term "direct" anywhere on the Fair Source page or in the FSL, and suggest it may be better to not introduce a new, and potentially confusing term when talking about FCL.

**Comment by ezekg** [comment]
I think you're reading into things a bit too much, since that's only used as an example of a common real-world competing use. My tweet wasn't comparing "competition" vs "direct competition" — it was comparing any competition vs no competition. But open to a PR if the FAQ's "direct" verbiage seems confusing to anybody else. I definitely want to be as clear as possible.

**Comment by Dieterbe** [comment]
This confirms my point again. What *is* direct competition? It seems you are using it to mean something else than (what i believe to be) the commonly accepted, well understood definition.

But from reading your text, it's not clear what the "direct" is referring to?

**Comment by ezekg** [comment]
My intention wasn't to draw a distinction between "direct" and "indirect" competition, but rather to emphasize the type of competition that the FCL is concerned with — namely, any use case that competes with the business interests of the author, and in this example, via a competing SaaS product in a way where the competition is immediate or obvious.

You're correct that the license itself doesn't make this distinction, and I agree that it's best to avoid introducing terms that could be misinterpreted.  I think it's just a difference in casual vs legal language. 

I've adjusted the wording in https://github.com/keygen-sh/fcl.dev/commit/d97c30268c837ed11ff47714b3f5d357b92ceb5f to better align with the language of the license itself and to prevent any confusion.

**Comment by Dieterbe** [comment]
looks good :+1:
